// <auto-generated />
namespace jdrive_backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class driver_passenger : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(driver_passenger));
        
        string IMigrationMetadata.Id
        {
            get { return "201901211843207_driver_passenger"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
